/**
 * Make Some Noise
 * Muriel
 * 
 * These are 2 tunes generated by PolySynth - both are taken directly from
 * Animal Crossing K.K. Slider songs (musical scale for my own reference,
 * AC uses natural pitches from G3 to E5). Tunes are loopable.
 */
"use strict";

let synth;
let scale = [`G3`, `A4`, `B4`, `C4`, `D4`, `E4`, `F4`, `G4`, `A5`, `B5`, `C5`, `D5`, `E5`];
let lullaby = [`E4`, `F4`, `G4`, `C5`, `D5`, `C5`, `E5`, `E5`, `E5`, `D5`, `A5`, `B5`, `C5`, `C5`, `C5`, `C5`];
let chorale = [`C4`, `D4`, `E4`, `F4`, `E4`, `E4`, `D4`, `E4`, `D4`, `D4`, `D4`, `D4`, `D4`, `D4`, `C4`, `C4`];
let currentNote = 0;
let interval;

function setup() {
    createCanvas(500,500);
    userStartAudio();

    synth = new p5.PolySynth();
}

function draw() {
    background(0);
}

function mousePressed() {
    if (interval === undefined) {
        interval = setInterval(playChorale, 750);
    } else {
        clearInterval(interval);
        interval = undefined;
    }
}

function keyPressed() {
    if (interval === undefined) {
        interval = setInterval(playLullaby, 750);
    } else {
        clearInterval(interval);
        interval = undefined;
    }
}

function playLullaby() {
    let note = lullaby[currentNote];
    synth.play(note, 0.1, 0, 0.7);
    if (currentNote === 6) {
        synth.play(`E5`, 0.1, 0, 2.25);
    }
    if (currentNote === 12) {
        synth.play(`C5`, 0.1, 0, 3);
    }
    if (currentNote === lullaby.length) {
        currentNote = 0;
    }
    currentNote++;
}

function playChorale() {
    let note = chorale[currentNote];
    synth.play(note, 0.1, 0, 0.7);
    if (currentNote === 4) {
        synth.play(`E4`, 0.1, 0, 1.45);
    }
    if (currentNote === 8) {
        synth.play(`D4`, 0.1, 0, 1.45);
    }
    if (currentNote === 10) {
        synth.play(`D4`, 0.1, 0, 2.95);
    }
    if (currentNote === 14) {
        synth.play(`C4`, 0.1, 0, 1.45);
    }
    if (currentNote === chorale.length) {
        currentNote = 0;
    }
    currentNote++;
}